### ISSUE TITLE
pest_io issues

### ISSUE THREAD

**Issue by porterma** [dharp/matk#2]
I downloaded the latest matk since it appears you have updated it for python 3. This is great! However, I ran into an issue with pest_io.py. My version of python complains about `file` in  `isinstance(f, file)` on line 23. Some searching on the internet suggests `file` is not a built in function in python 3. I changed it to `isinstance(f, io.IOBase` using the io package. That got me moving along however at line 56 `pd[m] = aeval(pstr)` caused me issues when using `%'{:10.4e}'.format(hk1)%` in my pest template file. I could not figure out the issue, but it was complaining about starargs. I bypassed this issue by using `~'%10.4e' % hk1~`. Just thought I'd let you know. I appreciate the package. Thanks.

**Comment by dharp** [comment]
Hi Mark, Sorry for not warning you about switching to Python3. Did you try running the test suite after making your changes? Did they all pass? If so, would you mind pushing your changes?
Thanks!
